// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Select$ReactHooksTemplate = require("./Select.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(Select$ReactHooksTemplate.make, {
                  values: /* :: */[
                    "one",
                    /* :: */[
                      "two",
                      /* :: */[
                        "three",
                        /* [] */0
                      ]
                    ]
                  ]
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
